@startuml
Actor User as human
human -> UI: Add new data entry
UI -> human: Display options for what types of data the user could add
human -> UI: Select and adjust options, filling in required criteria
alt User saves their changes
        human -> UI: Save changes
        UI -> Backend: Register new data type
        Backend -> DB: validate backend data is correct
        alt Data type is meal
                DB -> Recipe: Update list of known entires
        else Data type is food
                DB -> Food: Update list of known entries
        else Data type is exercise
                DB -> Exercise: Update list of known entries
        end
        DB -> UI: Acknowledge successful save
        UI -> human: Saved changes
else User changes their mind
        human -> UI: Discard/Leave UI
        UI -> human: Return to previous screen
end
@enduml
